project:
  type: website

website:
  title: "LightGBM Agentic AI Credit Risk"
  navbar:
    tools:
      - icon: github
        href: https://github.com/supriyasathe/IDC6940_LightGBM-agentic-ai-credit-risk
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Report
      - about.qmd

format:
  html:
    theme:
      light: lightly
      dark: darkly
    css: styles.css
    toc: true


